const TOGGLE_LOADER = "TOGGLE_LOADER";
const HIDE_LOADER = "HIDE_LOADER";
const SET_THEME = "SET_THEME";
const SET_USER = "SET_USER";
const SET_LANGUAGE = "SET_LANGUAGE";
const LOGOUT = "LOGOUT";


export {
    TOGGLE_LOADER, HIDE_LOADER, SET_USER, SET_THEME, SET_LANGUAGE, LOGOUT
}